### ISSUE TITLE
Support for more file formats like mov and heic

### ISSUE THREAD

**Issue by almquistj** [0xCCF4/PhotoSort#2]
This tool is great as it is!  I would love to see it handle more file extensions.  Perhaps using the nom-exif which seem to indicate that it supports reading exif information from mov and heic files too.

**Comment by 0xCCF4** [comment]
Good idea. I will have a look into that.

**Comment by 0xCCF4** [comment]
Video support is now available in version [0.1.5](https://github.com/0xCCF4/PhotoSort/releases/tag/v0.1.5).

**Comment by almquistj** [comment]
Works great. Thank you!
