### ISSUE TITLE
Choose a folder schema on moving

### ISSUE THREAD

**Issue by aseques** [0xCCF4/PhotoSort#33]
Hi, I found your tool and it really looks promising, unfortunately it doesn't yet fill on of my needs (or I haven't been able to find it in the documentation.
The scenario is that I am organizing de pictures in a structure of folders like 
`--target-dir /folder/destination/YYYY/MM`
This basically for two reasons:

- It makes it easier to look for a picture/video looking on the aproximate date it was taken
- It also overcomes the issue when there are many pictures and a flat directory is too large to view it's content in a rapid manner.

So I would be happy if that would be possible, thanks a lot

**Comment by 0xCCF4** [comment]
Hi, good idea, i will implement this.

**Comment by 0xCCF4** [comment]
From version `0.2.0` onward it is now possible to sort a library to subfolders.
I changed how one can specify a target file format.
For your use-case `--target-dir /folder/destination --file-format "{date?%Y}/{date?%M}/{type}{_:date}{-:name}{-:dup}"` could do the trick. This would sort the files to `/folder/destination/YYYY/MM/xxxx.zzz`

See https://docs.rs/chrono/latest/chrono/format/strftime/index.html for a full reference which date/time formatting codes can be put into `{date?...}`

**Comment by 0xCCF4** [comment]
You'r welcome. If you have any further ideas, just open a new issue.
