### ISSUE TITLE
[Feature request] Progress run | Log | Quiet run

### ISSUE THREAD

**Issue by roykrikke** [0xCCF4/PhotoSort#46]
Would be great to implement

1: If you want PhotoSort  to run with a progressbar (displaying only the progress and muting all progress messages (including errors)) use the flag --progress.

2: If you want PhotoSort to run and store the output in a log file use the flag --log. This flag can be used in conjunction with the flags --quiet or --progress.
--log=<PATH>/log.txt

3: If you want PhotoSort to run without any output (displaying only error messages, and muting all progress messages) use the flag --quiet.

**Comment by 0xCCF4** [comment]
Great idea.

Let me know, if I should implement this or you would like to try it. (#45)

**Comment by roykrikke** [comment]
Would be great if you could implement for now. Then I can start using the new feature. On top of this I will start my learning journey and start contributing at a later time.
