### ISSUE TITLE
[Feature request] Choice between lower or upper case letters for file extension

### ISSUE THREAD

**Issue by roykrikke** [0xCCF4/PhotoSort#49]
Would be great to implement if you could select lower or upper case letters for file extension. As it is currently implemented as default is always upper case letters for the output file extension. 

Flag could be --extension-mode upper OR lower OR original
[default: original]

**Comment by 0xCCF4** [comment]
Great idea.

I think that this would be easier to implement as filename formatter (like `{name}`, `{date}`, ...), having an optional parameter (like `{date?format}`) that can be either `lower`, `upper`, `copy` or something.

`{ext?lower}` would then be replaces by `png` and `{ext?upper}` by PNG.

Let me know, if I should implement this or you would like to try it. (#45)

**Comment by roykrikke** [comment]
Would be great if you could implement for now. Then I can start using the new feature. On top of this I will start my learning journey and start contributing at a later time.

**Comment by roykrikke** [comment]
Feature is working perfect, thanks!
